ToDo/Login/routes.py
from flask import blueprints, render_template, flash, redirect, url_for
from flask_login import current_user, login_user, logout_user, login_required

from ToDo.forms import LoginForm, RegisterForm
from ToDo.models import select_users_by_username, select_users_by_email, register_user

Login = blueprints.Blueprint('Login', __name__)

@Login.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        flash("You are already logged in!", category='error')
        return redirect(url_for('Views.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = select_users_by_username(form.username.data)
        if user != None and user.password == form.password.data:
            login_user(user, remember=form.remember.data)
            flash("Login successful!", category='success')
            return redirect(url_for('Views.home'))
        else:
            flash("Login unsuccessful! Please check username and password", category='error')
    return render_template('login.html', form=form, user=current_user)

@Login.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        flash("You are already logged in!", category='error')
        return redirect(url_for('Views.home'))

    form = RegisterForm()

    if form.validate_on_submit():
        if select_users_by_username(form.username.data):
            flash("Username already exists!", category='error')
        elif select_users_by_email(form.email.data):
            flash("Email already exists!", category='error')
        else:
            register_user(form.username.data, form.email.data, form.password.data)
            flash("Account created successfully!", category='success')
            return redirect(url_for('Login.login'))

    elif form.username.errors:
        flash ("Username Errors:" + str(form.username.errors), category='error')
    elif form.email.errors:
        flash("Email Errors:" + str(form.email.errors), category='error')
    elif form.password.errors:
        flash("Password Errors:" + str(form.password.errors), category='error')
    elif form.confirm_password.errors:
        flash("Confirm Password Errors:" + str(form.confirm_password.errors), category='error')

    return render_template('register.html', form=form, user=current_user)

@Login.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('Login.login'))

ToDo/Views/routes.py
from flask import blueprints, render_template, flash, redirect, url_for, request
from flask_login import login_required, current_user

from ToDo.models import User, Task, select_todo_lists, insert_todo_list, select_tasks, get_todo_list, insert_task, delete_todo_list, delete_task, get_task, update_task, todo_lists_task_count, select_all_tasks_by_userId
from ToDo.forms import TodoListForm, TaskForm

Views = blueprints.Blueprint('Views', __name__)

@Views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    user = User(current_user)

    todo_lists = todo_lists_task_count(user)

    form = TodoListForm()

    if form.validate_on_submit():
        insert_todo_list(form.title.data, user)
        flash("Todo List created successfully!", category='success')
        return redirect(url_for('Views.home'))

    return render_template('home.html', form=form, user=current_user, todo_list=todo_lists)

@Views.route('/<int:todo_list_id>', methods=['GET', 'POST'])
@login_required
def todo_list_delete(todo_list_id):
    
    delete_todo_list(todo_list_id)

    return redirect(url_for('Views.home'))


@Views.route('/todo_list/delete/<int:task_id>', methods=['GET', 'POST'])
@login_required
def task_delete(task_id):

    todo_list_id = get_task(task_id).todo_list_id
    
    delete_task(task_id)

    return redirect(request.referrer)

@Views.route('/todo_list/update/<int:task_id>', methods=['GET', 'POST'])
@login_required
def task_update(task_id):

    task  = get_task(task_id)

    update_task(task)
    
    return redirect(request.referrer)

@Views.route('/todo_list/<int:todo_list_id>', methods=['GET', 'POST'])
@login_required
def tasks(todo_list_id):
    user = User(current_user)    

    tasks = select_tasks(todo_list_id)
    todo_list = get_todo_list(todo_list_id)

    form = TaskForm()

    if form.validate_on_submit():
        insert_task(form.description.data, todo_list_id)
        flash("Task created successfully!", category='success')
        return redirect(url_for('Views.tasks', todo_list_id=todo_list_id))

    return render_template('tasks.html', user=current_user, form=form, todo_list=todo_list, tasks=tasks)

@Views.route('/todo_list/all_tasks', methods=['GET', 'POST'])
@login_required
def all_tasks():
    user = User(current_user)

    all_tasks = select_all_tasks_by_userId(user.userId)

    return render_template('all_tasks.html', user=current_user, tasks=all_tasks)

ToDo/templates/all_tasks.html
{% extends "layout.html" %}
{% block title %} All Tasks {% endblock %}

{% block content %}

<h1 align="center"> All Tasks </h1>

<ul class="list-group list-group-flush" id="tasks" style="display: flex; flex-direction: column;">
    {% for task in tasks %}
    <li class="list-group-item d-flex justify-content-between align-items-start">
        <div class="d-flex align-items-center"> <!-- Added align-items: center; -->
            <form action="{{ url_for('Views.task_update', task_id=task[0]) }}" method="POST" style="display: flex; align-items: center;"> <!-- Added styles here -->
                <input type="hidden" name="completed" value="{{ task[2] }}">
                <input type="checkbox" name="status" {% if task[2] %}checked{% endif %} onchange="this.form.submit()" style="zoom: 1.5;">
            </form>
            <div style="display: flex; flex-direction: column; margin-left: 10px;">
                <div><strong>Description:</strong> {{ task[1] }}</div>
                <div><strong>Todo List:</strong> {{ task[3] }}</div>
            </div>
        </div>
      
        <div class="d-flex">
            <form action="{{ url_for('Views.task_delete', task_id=task[0]) }}" method="POST" class="mr-2">
                <input type="submit" value="Delete" class="btn btn-danger">
            </form>
        </div>
    </li>
    {% endfor %}
</ul>


{% endblock %}

ToDo/templates/home.html
{% extends "layout.html" %}
{% block title %}ToDo Home{% endblock %}

{% block content %}

<h1 align="center"> Your Todo Lists </h1>
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.title(class="form-control form-control-lg")}}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
</form>
<ul class="list-group list-group-flush" id="todoList">
    {% for todo in todo_list %}
    <li class="list-group-item d-flex justify-content-between align-items-center">
      <div>
        <strong>Title:</strong> {{ todo[1] }}<br>
        <strong>Created At:</strong> {{ todo[2] }} <br>
        {{ todo[5]}} / {{ todo[4] }} tasks completed 
      </div>
  
      <div class="d-flex">
        <form action="{{ url_for('Views.tasks', todo_list_id=todo[0]) }}" method="POST" class="mr-2">
          <input type="submit" value="View" class="btn btn-primary">
        </form>
  
        <form action="{{ url_for('Views.todo_list_delete', todo_list_id=todo[0]) }}" method="POST" class="mr-2">
            <input type="submit" value="Delete" class="btn btn-danger">
          </form>
      </div>
    </li>
    {% endfor %}
  </ul>
  
{% endblock %}

ToDo/templates/layout.html
<!DOCTYPE html>
<html>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
        <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
        <title>{% block title %}Todo Preset Title{% endblock %}</title>
    </head>
    <body>
        <!-- Navbar -->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbar">
                {% if user.is_authenticated %}
                <!-- Home -->
                <a class="nav-item nav-link" href="{{ url_for('Views.home') }}">Home</a>
                <!-- All Tasks -->
                <a class="nav-item nav-link" href ="{{ url_for('Views.all_tasks') }}">All Tasks</a>
                <!-- Logout -->
                <a class="nav-item nav-link ml-auto" href="{{ url_for('Login.logout') }}">Logout</a>
                <!-- Logged in as username -->
                <span class="navbar-text">Logged in as user: {{ user[1] }}</span>
                {% else %}
                <!-- Login and Register -->
                <a class="nav-item nav-link" href="{{ url_for('Login.login') }}">Login</a>
                <a class="nav-item nav-link" href="{{ url_for('Login.register') }}">Register</a>
                {% endif %}
            </div>
        </nav>
        
        
        
        <!-- Flash error Messages -->
        {% with messages = get_flashed_messages(with_categories=true) %} 
        {% if messages %} 
        {% for category, message in messages %} 
        {% if category == 'error' %}
        <div class="alert alert-danger alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <!-- Flash other Messages -->
        {% else %}
        <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
        {% endif %} {% endfor %} {% endif %} {% endwith %}

        <!-- Page Content -->
        <div class="container" style="margin-top: 3%;">
            {% block content %}{% endblock %}
        </div>

        <!-- Bootstrap JS and jQuery -->
        <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

ToDo/templates/login.html
{% extends "layout.html" %}
{% block title %}Login{% endblock %}

{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Log in</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label")}}
                {{ form.username(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label")}}
                {{ form.password(class="form-control form-control-lg")}}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
        <div class="form-group">
            {{ form.remember.label }} {{ form.remember }}
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need an account? <a class="ml-2" href="{{ url_for('Login.register') }}">Register</a>
        </small>
    </div>
</div>
{% endblock %}

ToDo/templates/register.html
{% extends "layout.html" %}
{% block title %}Register{% endblock %}
{% block content %}
<div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">Register</legend>
            <div class="form-group">
                {{ form.username.label(class="form-control-label")}}
                {{ form.username(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{ form.email.label(class="form-control-label")}}
                {{ form.email(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{ form.password.label(class="form-control-label")}}
                {{ form.password(class="form-control form-control-lg")}}
            </div>
            <div class="form-group">
                {{ form.confirm_password.label(class="form-control-label")}}
                {{ form.confirm_password(class="form-control form-control-lg")}}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    <div class="border-top pt-3">
        <small class="text-muted">
            Already have an account? <a class="ml-2" href="{{ url_for('Login.login') }}">Login</a>
        </small>
    </div>
</div>
{% endblock %}

ToDo/templates/tasks.html
{% extends "layout.html" %}
{% block title %}Tasks{% endblock %}

{% block content %}

<h1 align="center"> Tasks for Todo List: {{ todo_list.title }}</h1>
<form method="POST">
    {{ form.hidden_tag() }}
    <div class="form-group">
        {{ form.description(class="form-control form-control-lg")}}
    </div>
    <div class="form-group">
        {{ form.submit(class="btn btn-outline-info") }}
    </div>
</form>

<ul class="list-group list-group-flush" id="tasks" style="display: flex; flex-direction: column;">
    {% for task in tasks %}
    <li class="list-group-item d-flex justify-content-between align-items-center" style="display: flex; align-items: center;">
        <div class="d-flex align-items-center">
            <form action="{{ url_for('Views.task_update', task_id=task[0]) }}" method="POST">
                <input type="hidden" name="completed" value="{{ task[2] }}">
                <label class="checkbox-container" style="display: flex; align-items: center;">
                    <input type="checkbox" name="status" {% if task[2] %}checked{% endif %} onchange="this.form.submit()" style="zoom: 1.5;">
                    <span class="checkmark"></span>
                </label>
            </form>
            <strong style="margin-left: 10px;">Description:&nbsp;</strong> {{ task[1] }}
        </div>
      
        <div class="d-flex">
            <form action="{{ url_for('Views.task_delete', task_id=task[0]) }}" method="POST" class="mr-2">
                <input type="submit" value="Delete" class="btn btn-danger">
            </form>
        </div>
    </li>
    {% endfor %}
</ul>


{% endblock %}